---
# defaults file for ansible-awx
namespace_name: awx
kubeconfig_context: docker-desktop
git_checkout_dest: /tmp/awx-operator
git_repo_tag: 2.3.0
awx_operator_image_base: quay.io/ansible/awx-operator
helm_values_file: "{{ playbook_dir }}/values.yaml"
web_hostname: awx.example.com
kube_env:
  NAMESPACE: "{{ namespace_name }}"
  IMAGE_TAG_BASE: "{{ awx_operator_image_base }}"
  KUBECONFIG: "{{ kubeconfig_path }}"