---
# ansible tasks file for ansible-awx
- block:
  - name: Remove AWX Helm Chart
    kubernetes.core.helm:
      name: awx
      release_namespace: "{{ namespace_name }}"
      state: absent

  - name: Remove k8s namespace
    kubernetes.core.k8s:
      name: "{{ namespace_name }}"
      api_version: v1
      kind: Namespace
      state: absent
      context: "{{ kubeconfig_context }}"

  - name: Remove CRD's
    kubernetes.core.k8s:
      definition:
        api_version: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        metadata:
          name: "{{ item }}"
      state: absent
    loop:
      - awxbackups.awx.ansible.com
      - awxrestores.awx.ansible.com
      - awxs.awx.ansible.com

  - name: Recursively remove AWX Operator Repo
    ansible.builtin.file:
      path: "{{ git_checkout_dest }}"
      state: absent
  tags: remove
