---
# ansible tasks file for ansible-awx
- block:
  - name: Remove AWX Helm Chart
    kubernetes.core.helm:
      name: awx
      release_namespace: "{{ namespace_name }}"
      state: absent

  - name: Remove k8s namespace
    kubernetes.core.k8s:
      name: "{{ namespace_name }}"
      api_version: v1
      kind: Namespace
      state: absent
      context: "{{ kubeconfig_context }}"
    register: namespace

  - name: Remove CRD's
    kubernetes.core.k8s:
      name: "{{ item }}"
      api_version: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      state: absent
    register: namespace
    loop:
      - AWXBackup
      - AWXRestore
      - AWX

  - name: Recursively remove AWX Operator Repo
    ansible.builtin.file:
      path: "{{ git_checkout_dest }}"
      state: absent
  tags: remove
