- name: Start GKeep container
  community.docker.docker_container:
    name: "{{ container_name }}"
    state: started
    image: python:3.11.0b4-bullseye
    command: ["sleep", "infinity"]
  register: container_info

- name: Copy setup script into the container
  community.docker.docker_container_copy_into:
    container: "{{ container_info.container.Config.Hostname }}"
    container_path: /tmp/gkeep_setup_script.sh
    mode: 755
    content: |
      #!/bin/bash
      apt-get update
      apt-get install -y jq
      pip install -U gkeep
      pip install urllib3==1.26.1
      pip install -U gpsoauth==1.0.2
      pip install python-bring-api
      mkdir -p ~/.config/gkeep/
      echo '{"username": "{{ gmail_username }}", "password": "{{ gmail_app_password }}"}' > ~/.config/gkeep/auth.json

- name: Run setup script
  community.docker.docker_container_exec:
    container: "{{ container_info.container.Config.Hostname }}"
    command: /tmp/gkeep_setup_script.sh  

- block:
  - name: Copy get gkeep note items script into the container
    community.docker.docker_container_copy_into:
      container: "{{ container_info.container.Config.Hostname }}"
      container_path: /tmp/gkeep_get_note.sh
      mode: 755
      content: |
        gkeep notes get --title {{ gkeep_note_name }} | sed 's/"//g' | sed -n '/.*☐ /s///p'

  - name: Get gkeep note items
    community.docker.docker_container_exec:
      container: "{{ container_info.container.Config.Hostname }}"
      command: sh /tmp/gkeep_get_note.sh
    register: gkeep_note_items

  - name: Set note items fact
    ansible.builtin.set_fact: gkeep_note_items="{{ gkeep_note_items.stdout_lines }}"

- block:
  - name: Copy python get Bring! list uuid script into container
    community.docker.docker_container_copy_into:
      container: "{{ container_info.container.Config.Hostname }}"
      container_path: /tmp/bring_get_uuid.sh
      mode: 755
      content: |
        #!/bin/bash
        GETLISTS=$(cat <<EOF
        from python_bring_api.bring import Bring
        bring = Bring("{{ bring_email }}", "{{ bring_password }}")
        bring.login()
        lists = bring.loadLists()
        print(lists)
        EOF
        )
        python -c "$GETLISTS"

  - name: Copy run get Bring! list uuid script into container
    community.docker.docker_container_copy_into:
      container: "{{ container_info.container.Config.Hostname }}"
      container_path: /tmp/run_bring_get_list.sh
      mode: 755
      content: |
        /tmp/bring_get_uuid.sh | sed 's/'\''/"/g' | jq '.lists[] | select(.name=="{{ bring_list_name }}")' | jq .listUuid

  - name: Run get Bring! list uuid script
    community.docker.docker_container_exec:
      container: "{{ container_info.container.Config.Hostname }}"
      command: sh /tmp/run_bring_get_list.sh
    register: bring_list_uuid

  - name: Set Bring! uuid fact
    ansible.builtin.set_fact: bring_list_uuid="{{ bring_list_uuid.stdout_lines[0] | replace('\"', '') }}"

  - name: Copy python add Bring! items script into container
    community.docker.docker_container_copy_into:
      container: "{{ container_info.container.Config.Hostname }}"
      container_path: /tmp/add_bring_items.py
      mode: 755
      content: |
        from python_bring_api.bring import Bring
        import sys
        item = sys.argv[1]
        bring = Bring("{{ bring_email }}", "{{ bring_password }}")
        bring.login()
        bring.saveItem("{{ bring_list_uuid }}", item, 'gkeep imported')

  - name: Run add Bring! items script
    community.docker.docker_container_exec:
      container: "{{ container_info.container.Config.Hostname }}"
      command: python /tmp/add_bring_items.py "{{ item }}"
    loop: "{{ gkeep_note_items }}"

  - name: Get gkeep {{ gkeep_note_name }} ID
    community.docker.docker_container_exec:
      container: "{{ container_info.container.Config.Hostname }}"
      command: gkeep notes get --title {{ gkeep_note_name }}
    register: bring_list_id

  - name: Set gkeep {{ gkeep_note_name }} ID fact
    set_fact:
      gkeep_note_id: "{{ bring_list_id.stdout_lines[0] | replace('(note id ', '') | replace(')', '') }}"

  - name: Delete items from gkeep {{ gkeep_note_name }} note
    community.docker.docker_container_exec:
      container: "{{ container_info.container.Config.Hostname }}"
      command: gkeep items delete {{ gkeep_note_id }} "{{ item }}"
    loop: "{{ gkeep_note_items }}"

- name: Kill GKeep container
  community.docker.docker_container:
    name: "{{ container_info.container.Config.Hostname }}"
    state: absent
