# Example playbook that calls the Gkeep to Bring! Role
---
- name: gkeep to bring!
  hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: gmail_username
      prompt: Enter your gmail username
      private: true
    - name: gmail_app_password
      prompt: Enter your gmail app password
      private: true
    - name: bring_email
      prompt: Enter your Bring! login email
      private: true
    - name: bring_password
      prompt: Enter your Bring! login password
      private: true

  tasks:    
    - include_role:
        name: philthynz/roles/gkeep-to-bring!
