name: Build and Push latest awx-ee image

on:
  release:
    types:
      - created

jobs:
  publish_and_push:
    runs-on: buildjet-16vcpu-ubuntu-2204-arm
    name: Build and push latest tag from main and on new commits
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-builder

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          ansible-builder build -v3 --tag=philthynz/awx-ee:latest --tag=philthynz/awx-ee:${{ github.event.release.tag_name }} --file=awx-ee/execution-environment.yml --container-runtime docker

      - name: Publish images
        run: |
          echo "Images that can be pushed"
          docker image ls | grep phil
          echo "Pushing images"
          docker push philthynz/awx-ee:${{ github.event.release.tag_name }}
          docker push philthynz/awx-ee:latest