name: Clone and Push ansible/awx image

on:
  workflow_dispatch:

env:
  AWX_VERSION: 22.0.0

jobs:
  publish_and_push:
    runs-on: ubuntu-20.04
    # runs-on: k3s-arm64-github-runner
    # runs-on: buildjet-16vcpu-ubuntu-2204-arm
    name: Clone AWX and push to DockerHub
    steps:

      - name: Check out AWX repo
        uses: actions/checkout@master
        with:
          repository: ansible/awx
          ref: ${{ env.AWX_VERSION }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install packages
        run: | 
          pip3 install ansible
          pip3 install docker

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: | 
          ansible-playbook tools/ansible/dockerfile.yml
          docker buildx build --platform linux/arm64 -t philthynz/awx:${{ env.AWX_VERSION }}-ghdev --push .

      # - name: Build AWX
      #   run: | 
      #     ansible-playbook tools/ansible/build.yml \
      #     -e ansible_python_interpreter=/usr/bin/python3 \
      #     -e awx_version=${{ env.AWX_VERSION }} \
      #     -e registry=philthynz \
      #     -e awx_image=ansible-awx \
      #     -e push=true \
      #     -vv
